import Head from 'next/head'
import dbConnect from '../lib/dbConnect'
import Movie from '../models/Movie'
import Link from 'next/link'


export default function Home({movies}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container">
        <h1>Movies</h1>
        <Link href="/new"
        className="btn btn-primary w-100 my-2" >
          Agregar
        </Link>
        {
          movies.map(({_id, title, plot})=>(
            <div className="card mb-2" key={_id}>
              <div className="card-body">
                <div className="h5 text-uppercase">{title} </div>
                <p className="fw-light">{plot} </p>
                <Link className="btn btn-success btn-sm" href={`/${_id}`}>
                Mas informacion...
                </Link>
              </div>
            </div>
          ))
        }
      </main>
    </>
  )
}

export async function getServerSideProps(){

  try {
    await dbConnect()
    const res = await Movie.find({})
    
    const movies = res.map(item=>{
      const movie = item.toObject()
      movie._id = movie._id.toString()
      return movie
    })
    return {props: {movies}}
  } catch (error) {
    console.log(error)
    return {props: {success: false, error: 'error'}};
    
  }
}
